spring:
  application:
    name: tridato-co-police

server:
  port: 8073

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost

tridato-co-police:
  ribbon:
    eureka:
      enabled: true
    listOfServers: localhost:50001,localhost:50002,localhost:50003
    ServerListRefreshInterval: 15000