spring:
  application:
    name: tridato-co-police

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost