spring:
  application:
    name: tridato-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost

zuul:
  routes:
    users:
      path: /police/**
      serviceId: tridato-co-police

tridato-co-police:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000