spring:
  application:
    name: service

server:
  port: 8071

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registerWithEureka: true
    fetchRegistry: true


  instance:
    hostname: localhost




